name: healthops_warehouse
version: "1.0.0"
config-version: 2

profile: healthops_warehouse

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  healthops_warehouse:
    marts:
      +materialized: table

seeds:
  healthops_warehouse:
    +quote_columns: false
