name: openhip
version: "1.0"
config-version: 2
profile: openhip
model-paths: ["models"]
models:
  openhip:
    raw:
      +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
